---
- name: Instalar Prometheus y Grafana en VM2
  hosts: vm2
  become: yes
  tasks:
    - name: Actualizar caché de apt
      apt:
        update_cache: yes

    - name: Instalar Prometheus
      apt:
        name: prometheus
        state: present

    - name: Agregar la clave del repositorio de Grafana
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present

    - name: Agregar el repositorio de Grafana
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Actualizar caché después de agregar el repositorio de Grafana
      apt:
        update_cache: yes

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present

    - name: Iniciar y habilitar Prometheus
      service:
        name: prometheus
        state: started
        enabled: yes

    - name: Iniciar y habilitar Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes
